variables:
  IMAGE_NAME: nodejs
  DOCKER_HOST: tcp://docker:2375/

build-job:
  image: docker:24-git
  stage: build
  services:
    - name: docker:24-dind
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$DOCKER_HUB_TOKEN"
  script:
    - docker build -f Dockerfile -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA musicapp23/$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA musicapp23/$DOCKER_IMAGE:latest
    - docker push musicapp23/$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push musicapp23/$DOCKER_IMAGE:latest
  only:
    - develop

deploy-job:
  image: alpine:latest
  stage: deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SSH_USER@$EC2_IPADDRESS "docker stop $DOCKER_IMAGE"
  - ssh $SSH_USER@$EC2_IPADDRESS "docker rmi --force musicapp23/$DOCKER_IMAGE"
  - ssh $SSH_USER@$EC2_IPADDRESS "docker system prune -f"
  - ssh $SSH_USER@$EC2_IPADDRESS "docker login -u $REGISTRY_USER -p $DOCKER_HUB_TOKEN"
  - ssh $SSH_USER@$EC2_IPADDRESS "docker pull musicapp23/$DOCKER_IMAGE"
  - ssh $SSH_USER@$EC2_IPADDRESS "docker run --name $DOCKER_IMAGE -p 3001:3001 -d musicapp23/$DOCKER_IMAGE"
  - ssh $SSH_USER@$EC2_IPADDRESS "docker logout"
  only:
  - develop
